<?php /** @var $this Project\Layout\Layout */

use Packaged\Dispatch\Dispatch;
use Packaged\Dispatch\ResourceStore;

?>
<!doctype html>
<html lang="en">
<head>
  <title>Skeleton Project</title>
  <meta charset="UTF-8">
  <?php echo Dispatch::instance()->store()->generateHtmlIncludes(ResourceStore::TYPE_CSS); ?>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<main>
  <?= $this->getContent(); ?>
</main>
<?php echo Dispatch::instance()->store()->generateHtmlIncludes(ResourceStore::TYPE_JS); ?>
</body>
</html>
